#FROM jupyter/base-notebook
#FROM jupyter/datascience-notebook
FROM ubuntu:18.04

ENV GID 1000
ENV UID 1000
ENV GROUP lotta
ENV USER lotta

#USER root

RUN groupadd -g 1000 lotta && useradd -m -u 1000 -g 1000 lotta

#ADD [--chown=$USER:$GROUP] . /home/$USER
WORKDIR /home/$USER

RUN chown -R $USER:$GROUP /home/*
RUN chown -R lotta:lotta /home/lotta
RUN apt update && \
    apt install -y python3 python3-pip
RUN pip3 install notebook

USER $USER

ENTRYPOINT jupyter notebook --ip 0.0.0.0  --port 8888 --allow-root
